"""Guard test: every pin in requirements.txt must satisfy requirements.in's constraints.

**The outage this exists to prevent (2026-08-01, P0 — fleet-wide).**

`requirements.txt` is generated by ``uv pip compile requirements.in``. On
2026-08-01 the committed lockfile contained::

    krepis==0.18.0
        # via
        #   -r requirements.in
        #   nousergon-lib

while ``requirements.in`` line 59 declared::

    krepis[openai]>=0.18.8

The lockfile **contradicted the file it claims to be compiled from**, which
means it was not produced by compiling the current `requirements.in` — a stale
compiled artifact was committed by `#538` (a signals refactor, merged
2026-08-01T13:38Z). It silently reverted `7cf4f7a` (2026-07-27), whose entire
purpose was raising that floor: *"fix(deps): krepis floor >=0.18.8 so SSM
stages get --correlation-id"*.

**Why this repo's lockfile is fleet-critical.** Every spot workload in the
fleet runs its SSM step through this repo's venv::

    /home/ec2-user/alpha-engine-dashboard/.venv/bin/python \\
      -m krepis.ssm_log_capture run --correlation-id <execution> --slug ... -- ...

`--correlation-id` was added in krepis 0.18.8. Below that floor the CLI does not
recognise the flag, argparse reports the *other* required arguments as missing,
and the step dies before doing any work::

    python -m krepis.ssm_log_capture run: error: the following arguments are
    required: --slug, --log

Measured: the 2026-08-01 weekly SF box launched 09:01Z (before `#538`) got
krepis 0.19.0 and ran. The recovery rerun's box launched 14:24Z (after) got
0.18.0, and **both** DataPhase2 and PredictorTraining died ~30s in. Same
command, same definition, different box. Any weekly / daily / EOD / groom
workload provisioned after 13:38Z was affected.

**Why a static test rather than a runtime one.** The failure surfaces on a
disposable spot box as an argparse usage error, which reads like a code defect
in the caller rather than a dependency regression — the 2026-08-01 diagnosis
cost several steps before the two boxes were compared. The contradiction is
visible in the diff, so it should be caught in the diff.
"""

from __future__ import annotations

import pathlib
import re

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_IN = _REPO_ROOT / "requirements.in"
_TXT = _REPO_ROOT / "requirements.txt"

# `name[extra1,extra2] >=1.2.3, <2` — capture name and the specifier tail.
_CONSTRAINT = re.compile(
    r"^(?P<name>[A-Za-z0-9._-]+)\s*(?:\[[^\]]*\])?\s*(?P<spec>[<>=!~].*)$"
)
_PIN = re.compile(r"^(?P<name>[A-Za-z0-9._-]+)==(?P<version>[^\s;]+)")


def _norm(name: str) -> str:
    """PEP 503 normalisation — `Foo.Bar_baz` and `foo-bar-baz` are one project."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _version_tuple(v: str) -> tuple:
    """Compare release segments numerically; ignore pre/post/local suffixes.

    Deliberately simple — this guard only needs ordering over the release
    numbers the fleet actually pins, and pulling in a full PEP 440 parser for a
    lockfile check would add a dependency to the thing being checked.
    """
    core = re.split(r"[^0-9.]", v, maxsplit=1)[0].rstrip(".")
    return tuple(int(p) for p in core.split(".") if p.isdigit())


def _declared_constraints() -> dict[str, list[tuple[str, str]]]:
    """{normalised name: [(operator, version), ...]} from requirements.in."""
    out: dict[str, list[tuple[str, str]]] = {}
    for raw in _IN.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        m = _CONSTRAINT.match(line)
        if not m:
            continue
        specs = []
        for part in m.group("spec").split(","):
            sm = re.match(r"\s*(==|>=|<=|>|<|!=|~=)\s*([^\s]+)\s*$", part)
            if sm:
                specs.append((sm.group(1), sm.group(2)))
        if specs:
            out.setdefault(_norm(m.group("name")), []).extend(specs)
    return out


def _compiled_pins() -> dict[str, str]:
    """{normalised name: pinned version} from requirements.txt."""
    out: dict[str, str] = {}
    for raw in _TXT.read_text().splitlines():
        m = _PIN.match(raw.strip())
        if m:
            out[_norm(m.group("name"))] = m.group("version")
    return out


def test_both_requirement_files_exist_and_parse():
    """A glob or parse that silently yields nothing would make this vacuous."""
    assert _IN.is_file() and _TXT.is_file()
    constraints, pins = _declared_constraints(), _compiled_pins()
    assert len(constraints) >= 10, f"parsed only {len(constraints)} constraints"
    assert len(pins) >= 50, f"parsed only {len(pins)} pins"


def test_krepis_pin_clears_the_correlation_id_floor():
    """THE REGRESSION (2026-08-01 P0), pinned explicitly.

    Named separately from the general sweep because this particular floor is
    load-bearing for every SSM-dispatched workload in the fleet, and because
    the general sweep would not survive someone deciding to relax the `.in`
    constraint — this asserts the capability, not just internal consistency.
    """
    pins = _compiled_pins()
    assert "krepis" in pins, "krepis must be pinned in the compiled lockfile"
    assert _version_tuple(pins["krepis"]) >= (0, 18, 8), (
        f"krepis=={pins['krepis']} is below the 0.18.8 floor that provides "
        f"`ssm_log_capture --correlation-id`. Every fleet spot workload runs "
        f"its SSM step through this repo's venv; below this floor they all die "
        f"with 'the following arguments are required: --slug, --log'. "
        f"See 7cf4f7a and the 2026-08-01 outage."
    )


@pytest.mark.parametrize("name", sorted(_declared_constraints()))
def test_compiled_pin_satisfies_declared_constraint(name):
    """The general form: the lockfile may not contradict its own source.

    `requirements.txt` says `# via -r requirements.in` for these packages. If a
    pin violates the constraint that produced it, the file was not compiled
    from the current `.in` — a stale artifact was committed, and whatever the
    `.in` change was meant to achieve has been silently reverted.
    """
    pins = _compiled_pins()
    if name not in pins:
        pytest.skip(f"{name} declared in requirements.in but not pinned (extras-only)")

    pinned = _version_tuple(pins[name])
    for op, want in _declared_constraints()[name]:
        target = _version_tuple(want)
        if op == ">=":
            ok = pinned >= target
        elif op == ">":
            ok = pinned > target
        elif op == "==":
            ok = pinned == target
        elif op == "<=":
            ok = pinned <= target
        elif op == "<":
            ok = pinned < target
        elif op == "!=":
            ok = pinned != target
        else:  # ~= and anything else — not modelled, do not guess
            continue
        assert ok, (
            f"requirements.txt pins {name}=={pins[name]} but requirements.in "
            f"declares {name}{op}{want}. The lockfile contradicts the file it "
            f"is compiled from — regenerate with "
            f"`uv pip compile requirements.in` rather than editing either by "
            f"hand, and check what the `.in` constraint was protecting."
        )
