#!/usr/bin/env python3
"""Render budget.yaml into a shell-sourceable manifest for box_health.sh.

WHY A GENERATED MANIFEST RATHER THAN box_health.sh PARSING YAML
---------------------------------------------------------------
box_health.sh is the box's watchdog. It must keep working when the box is
degraded -- which is exactly when a Python venv, a YAML library, or a slow
interpreter start is least trustworthy. So the watchdog stays pure bash and
sources a flat file, and the YAML parsing happens here, at install time.

WHY budget.yaml IS THE SOURCE
-----------------------------
It already enumerates every long-running service on the box. Before this, the
watchdog kept its OWN hand-maintained list, and the two drifted exactly as you
would expect: on 2026-07-27 the installed box_health.sh listed 8 services while
the copy in git listed 5, and NEITHER covered nginx -- the single ingress for
all ten vhosts. Six of fourteen services were unmonitored, and the failure
presented as green.

One list. Adding a service to the budget adds it to the watchdog.

Usage: generate-box-manifest.py [--output /etc/alpha-engine/box-services.conf]
Policy: nous-ergon-ops/policies/shared-application-host-policy.md T1-6.
"""
from __future__ import annotations

import argparse
import pathlib
import sys

try:
    import yaml
except ImportError:
    print("generate-box-manifest: PyYAML not available", file=sys.stderr)
    sys.exit(2)

BUDGET = pathlib.Path(__file__).parent / "systemd" / "resource-limits" / "budget.yaml"
DEFAULT_OUT = "/etc/alpha-engine/box-services.conf"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", default=DEFAULT_OUT)
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args()

    spec = yaml.safe_load(BUDGET.read_text())
    services, ports = [], []
    for svc in spec["services"]:
        services.append(svc["unit"])
        port = svc.get("port")
        if port is None:
            # Fail loud rather than silently monitoring one fewer port.
            print(f"generate-box-manifest: {svc['unit']} has no `port:` in "
                  f"budget.yaml — add one, or set `port: none` to opt out",
                  file=sys.stderr)
            return 1
        if str(port) != "none":
            ports.append(str(port))

    body = [
        "# GENERATED by infrastructure/generate-box-manifest.py from",
        "# infrastructure/systemd/resource-limits/budget.yaml — do not hand-edit.",
        "#",
        "# Sourced by box_health.sh. Hand edits are drift: the next install",
        "# regenerates this file and silently discards them.",
        "",
        f"SERVICES=({' '.join(services)})",
        f"PORTS=({' '.join(ports)})",
        "",
        "# Count of enabled non-oneshot units expected on this box. box_health.sh",
        "# compares this against reality and alerts if the box has grown a service",
        "# that nobody added to the budget — the guard that stops this list from",
        "# silently falling behind again.",
        f"EXPECTED_SERVICE_COUNT={len(services)}",
        "",
    ]
    text = "\n".join(body)

    if args.stdout:
        print(text, end="")
        return 0

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({len(services)} services, {len(ports)} ports)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
