#!/usr/bin/env python3
"""Render budget.yaml into a shell-sourceable manifest for box_health.sh.

WHY A GENERATED MANIFEST RATHER THAN box_health.sh PARSING YAML
---------------------------------------------------------------
box_health.sh is the box's watchdog. It must keep working when the box is
degraded -- which is exactly when a Python venv, a YAML library, or a slow
interpreter start is least trustworthy. So the watchdog stays pure bash and
sources a flat file, and the YAML parsing happens here, at install time.

WHY budget.yaml IS THE SOURCE
-----------------------------
It already enumerates every long-running service on the box. Before this, the
watchdog kept its OWN hand-maintained list, and the two drifted exactly as you
would expect: on 2026-07-27 the installed box_health.sh listed 8 services while
the copy in git listed 5, and NEITHER covered nginx -- the single ingress for
all ten vhosts. Six of fourteen services were unmonitored, and the failure
presented as green.

One list. Adding a service to the budget adds it to the watchdog.

Usage: generate-box-manifest.py [--output /etc/alpha-engine/box-services.conf]
Policy: nous-ergon-ops/policies/shared-application-host-policy.md T1-6.
"""
from __future__ import annotations

import argparse
import pathlib
import sys

try:
    import yaml
except ImportError:
    print("generate-box-manifest: PyYAML not available", file=sys.stderr)
    sys.exit(2)

BUDGET = pathlib.Path(__file__).parent / "systemd" / "resource-limits" / "budget.yaml"
DEFAULT_OUT = "/etc/alpha-engine/box-services.conf"


_UNITS = {"s": 1, "m": 60, "h": 3600, "d": 86400}


def parse_duration(unit: str, raw) -> int:
    """`max_staleness` (e.g. "26h", "45m", "8d") -> seconds.

    box_health.sh stays pure bash (see the module docstring), so the arithmetic
    happens here at install time and the watchdog only ever compares integers.

    Raises rather than defaulting: a threshold that silently became a wrong
    number is worse than no threshold, because it reports as covered. Bad input
    must break the install, where it is visible, not the watchdog at 03:00.
    """
    text = str(raw).strip()
    if not text or text[-1] not in _UNITS or not text[:-1].isdigit():
        raise ValueError(
            f"{unit}: max_staleness must be <integer><s|m|h|d> (got {raw!r})"
        )
    seconds = int(text[:-1]) * _UNITS[text[-1]]
    if seconds <= 0:
        raise ValueError(f"{unit}: max_staleness must be positive (got {raw!r})")
    return seconds


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", default=DEFAULT_OUT)
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args()

    spec = yaml.safe_load(BUDGET.read_text())
    services, ports = [], []
    for svc in spec["services"]:
        services.append(svc["unit"])
        port = svc.get("port")
        if port is None:
            # Fail loud rather than silently monitoring one fewer port.
            print(f"generate-box-manifest: {svc['unit']} has no `port:` in "
                  f"budget.yaml — add one, or set `port: none` to opt out",
                  file=sys.stderr)
            return 1
        if str(port) != "none":
            ports.append(str(port))

    excluded = [e["unit"] for e in spec.get("manifest_exclude", [])]
    timers = [(t["unit"], parse_duration(t["unit"], t["max_staleness"]))
              for t in spec.get("timers", [])]
    state_paths = [e["path"] for e in spec.get("state", [])]

    body = [
        "# GENERATED by infrastructure/generate-box-manifest.py from",
        "# infrastructure/systemd/resource-limits/budget.yaml — do not hand-edit.",
        "#",
        "# Sourced by box_health.sh. Hand edits are drift: the next install",
        "# regenerates this file and silently discards them.",
        "",
        f"SERVICES=({' '.join(services)})",
        f"PORTS=({' '.join(ports)})",
        "",
        "# Units deliberately outside coverage (OS plumbing, templates). box_health.sh",
        "# reports any enabled non-oneshot unit that is in neither list — so a new app",
        "# service surfaces as an alert instead of going quietly unmonitored.",
        "#",
        "# By NAME, not a count: a count cannot say what is missing, and a count-based",
        "# version of this check false-alarmed on exactly these units when first",
        "# deployed 2026-07-27.",
        f"MONITOR_EXCLUDE=({' '.join(excluded)})",
        "",
        "# Per-timer dead-man budget in SECONDS (config-I5209). Answers the",
        "# question the scheduler-state check cannot: did the job actually run,",
        "# and did it succeed? A timer failing on every fire is `active`,",
        "# `waiting`, with a valid next elapse — indistinguishable from healthy",
        "# without this. box_health.sh names any enabled timer missing a row.",
        "declare -A TIMER_MAX_STALENESS=(",
        *[f'    ["{unit}"]={secs}' for unit, secs in timers],
        ")",
        "",
        "# Durable state declared in budget.yaml::state[] (T1-4). box_health.sh",
        "# names any on-disk database NOT matching one of these, because",
        "# undeclared state is neither backed up nor knowingly accepted as lost —",
        "# it is simply unconsidered, which is what T1-4 calls a defect.",
        "# Entries may be globs (e.g. /home/ec2-user/*/.env).",
        f"STATE_DECLARED=({' '.join(state_paths)})",
        "",
    ]
    text = "\n".join(body)

    if args.stdout:
        print(text, end="")
        return 0

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({len(services)} services, {len(ports)} ports)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
