#!/bin/bash
# install-resource-limits.sh — render and install systemd drop-ins from budget.yaml.
#
# The drop-ins are GENERATED, never hand-edited on the box. budget.yaml is the
# single source of truth; check_memory_budget.py --installed asserts the box
# matches it. Hand-editing a drop-in is drift, and the check will fail.
#
# Before this existed, the limits lived only on the box (alpha-engine-config
# -I4440): they were invisible to review, unreproducible on a rebuild, and
# silently lost on any instance replacement.
#
# Usage:
#   sudo ./install-resource-limits.sh            # install + daemon-reload
#   sudo ./install-resource-limits.sh --dry-run  # print what would change
#
# Policy: nous-ergon-ops/policies/shared-application-host-policy.md T1-1, T1-2.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUDGET="$HERE/systemd/resource-limits/budget.yaml"

# 99- so this drop-in sorts LAST and therefore wins. systemd merges drop-ins in
# alphabetical order with later files overriding earlier ones, and the legacy
# hand-written files on this box are named `override.conf` and `10-memory.conf`.
# A `10-` prefix here would have been silently overridden by `override.conf` --
# the budget would have been installed and had no effect.
DROPIN_NAME="99-resource-limits.conf"

# Legacy hand-written memory drop-ins that this file supersedes. Every one was
# verified 2026-07-27 to contain ONLY [Service] + Memory{High,Max} — no
# ExecStart, Environment, or other settings — so removing them loses nothing.
# They are removed rather than left in place because dead config that no longer
# takes effect is exactly the drift this mechanism exists to eliminate.
# NOTE: morning-signal.service.d/10-memory.conf is deliberately NOT touched —
# morning-signal is timer-driven, out of this budget's scope, and its drop-in
# is already tracked in VCS.
LEGACY_NAMES=("override.conf" "10-memory.conf")

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

[[ -f "$BUDGET" ]] || { echo "missing $BUDGET" >&2; exit 1; }

PY=$(command -v python3)
"$PY" -c 'import yaml' 2>/dev/null || { echo "PyYAML required" >&2; exit 1; }

# Refuse to install a budget that does not fit. Installing an over-budget set
# is exactly the failure this whole mechanism exists to prevent, so the
# installer is the wrong place to be permissive.
if ! "$PY" "$HERE/check_memory_budget.py" --declared --quiet; then
    echo "REFUSING to install: declared budget exceeds the ceiling (see above)." >&2
    exit 1
fi

CHANGED=0
while IFS='|' read -r unit user high max; do
    [[ -z "$unit" ]] && continue
    dir="/etc/systemd/system/${unit}.d"
    target="${dir}/${DROPIN_NAME}"

    # USER DIRECTIVE: set when budget.yaml declares a per-service user.
    # nginx already runs as its own user — it has NO user field and the
    # User= line is omitted (nginx owns its own service file's User=).
    user_directive=""
    if [[ -n "$user" ]]; then
        user_directive="User=${user}"
    fi

    # REMOVEIPC: safe only when the service has its own user. With a shared
    # identity (ec2-user), RemoveIPC=yes would destroy IPC objects belonging
    # to the other twelve services when this one stops. Per alpha-engine-
    # config-I4490 and the budget.yaml sandboxing section, this was
    # deliberately omitted until per-service users land.
    remove_ipc=""
    if [[ -n "$user" ]]; then
        remove_ipc="RemoveIPC=yes"
    fi

    rendered=$(cat <<EOF
# GENERATED by infrastructure/install-resource-limits.sh from
# infrastructure/systemd/resource-limits/budget.yaml — do not hand-edit.
# Hand edits are drift and will fail check_memory_budget.py --installed.
[Unit]
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
MemoryAccounting=yes
MemoryHigh=${high}
MemoryMax=${max}
Restart=always
RestartSec=5s
OOMPolicy=stop
${user_directive}
${remove_ipc}

# ── sandboxing (alpha-engine-config-I4490) ──────────────────────────────
# Thirteen services across eight products share the single ec2-user identity.
# Without these, one compromised service reads every other service's material:
# the ~/.netrc deploy PAT, both Cloudflare Origin private keys, 17 git
# checkouts, and whatever the other twelve have resolved from SSM.
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=full
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
EOF
)

    # Retire superseded legacy drop-ins for this unit first. Left in place they
    # are dead config (99- wins), which is drift waiting to confuse someone.
    for legacy in "${LEGACY_NAMES[@]}"; do
        lpath="${dir}/${legacy}"
        [[ -f "$lpath" ]] || continue
        if grep -qvE '^\s*($|#|\[Service\]|MemoryAccounting=|MemoryHigh=|MemoryMax=)' "$lpath"; then
            echo "SKIP removing $lpath — contains settings beyond memory; review by hand" >&2
            continue
        fi
        CHANGED=1
        if [[ $DRY_RUN -eq 1 ]]; then
            echo "would remove superseded $lpath"
        else
            rm -f "$lpath"
            echo "removed superseded $lpath"
        fi
    done

    if [[ -f "$target" ]] && [[ "$(cat "$target")" == "$rendered" ]]; then
        continue
    fi

    CHANGED=1
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "would write $target (MemoryHigh=$high MemoryMax=$max)"
    else
        mkdir -p "$dir"
        printf '%s\n' "$rendered" > "$target"
        chmod 644 "$target"
        echo "wrote $target"
    fi
done < <("$PY" - "$BUDGET" <<'PYEOF'
import sys, yaml
spec = yaml.safe_load(open(sys.argv[1]))
for s in spec["services"]:
    user = s.get("user", "")
    print(f"{s['unit']}|{user}|{s['memory_high']}|{s['memory_max']}")
PYEOF
)

if [[ $DRY_RUN -eq 1 ]]; then
    echo "(dry run — nothing written)"
    exit 0
fi

if [[ $CHANGED -eq 0 ]]; then
    echo "no changes; drop-ins already match budget.yaml"
    exit 0
fi

systemctl daemon-reload
echo "daemon-reload done."

# Regenerate the watchdog's service/port manifest from the same budget.yaml, so
# adding a service to the budget also puts it under box_health.sh coverage.
# Two lists is how the watchdog fell six services behind in the first place.
echo
"$PY" "$HERE/generate-box-manifest.py"
echo
echo "Drop-ins are installed but NOT yet applied to running processes."
echo "New MemoryMax takes effect on the running cgroup immediately;"
echo "Restart=/RestartSec= apply to the NEXT start of each unit."
echo
echo "Verify with: $HERE/check_memory_budget.py --installed"
