#!/bin/bash
# install-resource-limits.sh — render and install systemd drop-ins from budget.yaml.
#
# The drop-ins are GENERATED, never hand-edited on the box. budget.yaml is the
# single source of truth; check_memory_budget.py --installed asserts the box
# matches it. Hand-editing a drop-in is drift, and the check will fail.
#
# Before this existed, the limits lived only on the box (alpha-engine-config
# -I4440): they were invisible to review, unreproducible on a rebuild, and
# silently lost on any instance replacement.
#
# Usage:
#   sudo ./install-resource-limits.sh            # install + daemon-reload
#   sudo ./install-resource-limits.sh --dry-run  # print what would change
#
# Policy: nous-ergon-ops/policies/shared-application-host-policy.md T1-1, T1-2.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUDGET="$HERE/systemd/resource-limits/budget.yaml"
DROPIN_NAME="10-resource-limits.conf"
DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

[[ -f "$BUDGET" ]] || { echo "missing $BUDGET" >&2; exit 1; }

PY=$(command -v python3)
"$PY" -c 'import yaml' 2>/dev/null || { echo "PyYAML required" >&2; exit 1; }

# Refuse to install a budget that does not fit. Installing an over-budget set
# is exactly the failure this whole mechanism exists to prevent, so the
# installer is the wrong place to be permissive.
if ! "$PY" "$HERE/check_memory_budget.py" --declared --quiet; then
    echo "REFUSING to install: declared budget exceeds the ceiling (see above)." >&2
    exit 1
fi

CHANGED=0
while IFS='|' read -r unit high max; do
    [[ -z "$unit" ]] && continue
    dir="/etc/systemd/system/${unit}.d"
    target="${dir}/${DROPIN_NAME}"

    rendered=$(cat <<EOF
# GENERATED by infrastructure/install-resource-limits.sh from
# infrastructure/systemd/resource-limits/budget.yaml — do not hand-edit.
# Hand edits are drift and will fail check_memory_budget.py --installed.
[Unit]
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
MemoryAccounting=yes
MemoryHigh=${high}
MemoryMax=${max}
Restart=always
RestartSec=5s
OOMPolicy=restart
EOF
)

    if [[ -f "$target" ]] && [[ "$(cat "$target")" == "$rendered" ]]; then
        continue
    fi

    CHANGED=1
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "would write $target (MemoryHigh=$high MemoryMax=$max)"
    else
        mkdir -p "$dir"
        printf '%s\n' "$rendered" > "$target"
        chmod 644 "$target"
        echo "wrote $target"
    fi
done < <("$PY" - "$BUDGET" <<'PYEOF'
import sys, yaml
spec = yaml.safe_load(open(sys.argv[1]))
for s in spec["services"]:
    print(f"{s['unit']}|{s['memory_high']}|{s['memory_max']}")
PYEOF
)

if [[ $DRY_RUN -eq 1 ]]; then
    echo "(dry run — nothing written)"
    exit 0
fi

if [[ $CHANGED -eq 0 ]]; then
    echo "no changes; drop-ins already match budget.yaml"
    exit 0
fi

systemctl daemon-reload
echo "daemon-reload done."
echo
echo "Drop-ins are installed but NOT yet applied to running processes."
echo "New MemoryMax takes effect on the running cgroup immediately;"
echo "Restart=/OOMPolicy= apply to the NEXT start of each unit."
echo
echo "Verify with: $HERE/check_memory_budget.py --installed"
